config/routes.rb
EventApp::Application.routes.draw do
  
  mount Ckeditor::Engine => "/ckeditor"
  
  get "admin/new"

  get "admin/create"

  devise_for :admins, :controllers => { :sessions => "admin" }

  get "registration/new"

  devise_for :users, :controllers => { :sessions => "users", :registrations => "registration" }

  resources :events
    match 'eventFeedRss/:ids' => 'Events#get_rss_feed', :as => 'event_feed'
    match 'allEventFeedRss' => 'Events#get_all_rss_feed', :as => 'all_event_feed'
    match 'getEventsByFormat/:attr/:value' => 'Events#get_events_by_format'
    match 'pdfEvent/:id' => 'Events#pdf_event', :as => 'pdf_event'
    match 'pdfEvents/:ids' => 'Events#pdf_events', :as => 'pdf_events'
    match 'icsEvent/:id' => 'Events#ics_event', :as => 'ics_event'
    
  get "venue/index"
  
  controller :Venue do
    match 'eventHighlights/:cat/:highlight' => :index, :as => 'event_highlight'
    match 'federalCountry/:country' => :get_federal_country, :as => 'get_federal_country'
    match 'venue/:city' => :get_venue, :as => 'get_venue'
    match 'catMainEvents/:cat' => :get_main_cat_events, :as => 'get_main_cat_events'
    match 'catSubEvents/:cat' => :get_sub_cat_events, :as => 'get_sub_cat_events'
    match 'date/:start_date' => :get_events_by_date
    match 'contact' => :contact, :as => 'contact'
    match 'sendContactMail' => :send_contact_mail, :as => 'send_contact_mail'
    match 'searchSurroundingEvents' => :search_surrounding_events, :as => 'search_surrounding_events'
    match 'locationSearch' => :get_events_by_geocoding, :as => 'get_events_by_geocoding'
    match 'userlist' => :get_user_list, :as => 'get_user_list'
    match 'sitemap.xml' => :sitemap
  end
  
  controller :Ajax do
    match 'searchForEvents/:search' => :search_events
  end
  
  root :to => 'Venue#index'
  # See how all your routes lay out with "rake routes"

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :city, :email, :end_date, :end_date_time, :regional_highlight, :federal_highlight, :main_category, :costs, :address, :province, :region, :description, :start_date, :start_date_time, :sub_category, :tel_nr, :title, :venue, :venue_url, :image, :image_url, :repeat_dates, :sponsored, :latitude, :longitude, :user_id, :user
  validates :title, :presence => true
  validates :region, :presence => true
  validates :province, :presence => true
  validates :main_category, :presence => true
  validates :venue, :presence => true
  validates :description, :presence => true
  validates :start_date, :presence => true
  validates :end_date, :presence => true
  validates :start_date_time, :presence => true
  validates :address, :presence => true
  
  belongs_to :user
  
  geocoded_by :address
  after_validation :geocode
  
  has_attached_file :image, 
                    :styles => { :medium => "300x300>", :thumb => "100x100>" }
                    #:default_style => :thumb,
                    #:url => "/images/:basename.:extension",
                    #:path => ":rails_root/public/images/:basename.:extension"
  
  def self.search(value)
    if value
      hits = []
      hits += find(:all, :conditions => ["title like ? OR city like ? OR description like ?", '%' + value + '%', '%' + value + '%', '%' + value + '%'], :order => "start_date asc")
      if hits.empty?
        hits += find(:all, :conditions => ["title like ? OR city like ? OR description like ?", '%' + value.downcase + '%', '%' + value.downcase + '%', '%' + value.downcase + '%'], :order => "start_date asc")
      end
      hits
    else
      order('start_date asc')
    end
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include ActionView::Helpers::SanitizeHelper 
  
  before_filter :get_event_cats_and_venues, :only => [:new, :edit]
  
  before_filter :get_navi_vars, :only => [:show]
  
  def show
    @event = Event.find(params[:id])
  end
  
  def new
    @event = Event.new
    
    if request.location && request.location.city.length > 0
      @location = request.location.city + ', ' + request.location.country
    else
      @location = ''
    end
    check_logged_in_user
  end
  
  def create
    event = Event.new
    
    set_event_attr event, params[:event]
    
    if event.save
      redirect_to :root, :notice => 'Veranstaltung erfolgreich hinzugefügt'
    else
      render 'new'
    end
  end
  
  def edit
    @event = Event.find(params[:id])
    check_logged_in_user
  end
  
  def update
    event = Event.find(params[:id])
    
    set_event_attr event, params[:event]
    
    if event.save
      redirect_to :root, :notice => 'Veranstaltung erfolgreich bearbeitet.'
    else
      render 'edit'
    end
  end
  
  def destroy
    Event.find(params[:id]).destroy
    redirect_to :root, :notice => 'Veranstaltung erfolgreich gelöscht.'
  end
  
  def pdf_event
    event = Event.find(params[:id])
    html_stripped_description = strip_tags(event.description)
    
    pdf_path = (Prawn::Document.generate((event.title + ".pdf")) do
              move_down 10
              if event.federal_highlight
                text 'Bundes-Highlight:', :size => 20
              elsif event.regional_highlight
                text 'Regional-Highlight:', :size => 20
              elsif !event.federal_highlight && !event.regional_highlight
                text 'Veranstaltung:', :size => 20
              end
              
              move_down 5
              text event.title, :size => 18
              move_down 2
              text event.main_category << '/' << event.sub_category
              move_down 2
              text 'Start-Datum: ' << event.start_date.strftime('%d.%b %Y')
              move_down 2
              text 'Start-Zeit: ' << event.start_date_time.strftime('%H:%M:%S')
              move_down 2
              text 'Ende-Datum: ' << event.end_date.strftime('%d.%b %Y')
              move_down 2
              text 'Ende-Zeit: ' << event.end_date_time.strftime('%H:%M:%S')
              
              if event.repeat_dates.length > 0
                move_down 2
                text 'Nächste-Daten: ' << event.start_date.strftime('%Y/%m/%d')
              end
              
              if event.image.exists?
                image event.image.path, :position => :right, :vposition => 10, :width => 150, :height => 100
              elsif event.image_url && event.image_url.length > 0 && URI.parse(event.image_url).kind_of?(URI::HTTP)
                begin 
                  image open(event.image_url).path, :position => :right, :vposition => 10, :width => 150, :height => 100
                rescue OpenURI::HTTPError => response
                  Rails.logger.info 'fetching File: ' << event.image_url << ' resulted to http-status: ' << response.exception.io.status[0].to_s
                end
              end
              
              move_down 3
              text html_stripped_description
              
              move_down 6
              t = make_table([ 
                             ['Veranstaltungsort', event.venue],
                             ['Adresse', event.address],
                             ['Kosten', if event.costs.length > 0 then event.costs else 'Keine Kosten angegeben' end],
                             ['Website', if event.venue_url.length > 0 then event.venue_url else 'Keine Website angegeben' end],
                             ['Email', if event.email.length > 0 then event.email else 'Keine Email angegeben' end],
                             ['Tel. Nr.', if event.tel_nr.length > 0 then event.tel_nr else 'Keine Website angegeben' end] ])
              t.draw
              
           end).path
    send_file( pdf_path, :type => 'application/pdf',:disposition => 'inline')
  end
  
  def pdf_events
    events = []
    html_stripped_descriptions = []
    
    params[:ids].split(',').each do |id|
      events << Event.find(id)
      html_stripped_descriptions << CGI::unescapeHTML(strip_tags(Event.find(id).description))
    end
    
    pdf_path = (Prawn::Document.generate((events[0].title + ".pdf")) do
              move_down 10
              text 'Gelistete Veranstaltungen: ', :size => 22
              move_down 6
              
              events.each_with_index do |event, index|
                move_down 10
                if event.federal_highlight
                  text 'Bundes-Highlight:', :size => 20
                elsif event.regional_highlight
                  text 'Regional-Highlight:', :size => 20
                elsif !event.federal_highlight && !event.regional_highlight
                  text 'Veranstaltung:', :size => 20
                end
                
                move_down 5
                text event.title, :size => 18
                move_down 2
                text event.main_category << '/' << event.sub_category
                move_down 4
                text 'Start-Datum: ' << event.start_date.strftime('%d.%b %Y')
                move_down 2
                text 'Start-Zeit: ' << event.start_date_time.strftime('%H:%M:%S')
                move_down 2
                text 'Ende-Datum: ' << event.end_date.strftime('%d.%b %Y')
                move_down 2
                text 'Ende-Zeit: ' << event.end_date_time.strftime('%H:%M:%S')
                
                if event.repeat_dates.length > 0
                  move_down 2
                  text 'Nächste-Daten: ' << event.start_date.strftime('%d.%b %Y')
                end
                
                if event.image.exists?
                  image event.image.path, :position => :right, :position => 340, :vposition => 10, :width => 150, :height => 100
                elsif event.image_url && event.image_url.length > 0 && URI.parse(event.image_url).kind_of?(URI::HTTP)
                  begin
                    image open(event.image_url).path, :position => :right, :position => 240, :vposition => 10, :width => 150, :height => 100
                  rescue OpenURI::HTTPError => response
                    Rails.logger.info 'fetching File: ' << event.image_url << ' resulted to http-status: ' << response.exception.io.status[0].to_s
                  end
                end
                
                move_down 3
                text html_stripped_descriptions[index]
                
                move_down 6
                t = make_table([ 
                               ['Veranstaltungsort', event.venue],
                               ['Adresse', event.address],
                               ['Kosten', if event.costs.length > 0 then event.costs else 'Keine Kosten angegeben' end],
                               ['Website', if event.venue_url.length > 0 then event.venue_url else 'Keine Website angegeben' end],
                               ['Email', if event.email.length > 0 then event.email else 'Keine Email angegeben' end],
                               ['Tel. Nr.', if event.tel_nr.length > 0 then event.tel_nr else 'Keine Website angegeben' end] ])
                t.draw
                
                start_new_page if events.last != event
              end
           end).path
    send_file( pdf_path, :type => 'application/pdf',:disposition => 'inline')
  end
  
  def ics_event
    
    event = Event.find(params[:id])
    
    cal = Icalendar::Calendar.new
    cal.event do
      dtstart       event.start_date.to_s
      dtend         event.end_date.to_s
      summary       event.title
      description   event.description
      klass         "Public"
    end

    send_data(cal.to_ical, :filename=>"mycal.ics", :disposition=>"inline; filename=mycal.ics", :type=>"text/calendar")
  end
  
  def get_all_rss_feed
    @events = Event.all
    
    respond_to do |format|
      format.rss { render 'get_rss_feed' }
    end
  end
  
  def get_rss_feed
    ids = params[:ids].split(',')
    @events = []
    
    ids.each do |id|
      @events << Event.find(id)
    end
    
    respond_to do |format|
      format.rss { render rss: @events }
    end
  end
  
  def get_events_by_format
    @events = []
    values = params[:value].split(',')
    values.each do |val|
      event = Event.where(params[:attr] => val)
      if !event.empty?
        event.each do |e|
          @events << e
        end
      end
    end
    
    @events = @events.sort
    
    respond_to do |format|
      format.xml { render xml: @events.to_xml }
      format.json { render json: @events.to_json }
    end
  end
  
  private
  
  def get_event_cats_and_venues
    
    @federal_countries = { 'Wähle Bundesland' => '' }
    @federal_countries = @federal_countries.merge(Venues.get_federal_countries)
    
    @venues  = []
    Venues.get_federal_countries.each do |k,v|
      venue = Venues.get_venues k
      venue = venue.sort
      @venues << { k =>  venue }
    end
    
    @main_event_cats = { 'Wähle Hauptkategorie' => '' }
    @main_event_cats = @main_event_cats.merge(Categories.get_main_cats)
    
    @event_cats  = []
    Categories.get_main_cats.each do |k,v|
      sub_cat = Categories.get_sub_cats k
      sub_cat = sub_cat.sort
      @event_cats << { k =>  sub_cat }
    end
    
  end
  
  
  def set_event_attr event, params
    
    event_start_time = params['start_date'] + ' ' + params['start_date_time']
    event_end_time = params['end_date'] + ' ' + params['end_date_time']
    reg_highlight = if params['regional_highlight'].to_i == 0 then false else true end
    fed_highlight = if params['federal_highlight'].to_i == 0 then false else true end
    sponsored = if params['sponsored'].to_i == 0 then false else true end
    
    start_date = Date.parse(event_start_time)

app/helpers/events_helper.rb
module EventsHelper
  def convert_date_to_time date
    if date
      date.to_time
    else
      date
    end
  end
end

app/views/events/edit.html.erb
<p><%= link_to 'Home', root_path %></p>
<h2>Veranstaltung bearbeiten</h2>
<%= render 'event_form' %>

<script type="text/javascript">

  $(document).ready(function() {
  
    $("#event_start_date").datepicker({ 'format': 'yyyy/mm/dd' });
    $("#event_end_date").datepicker({ 'format': 'yyyy/mm/dd' });
    
    $("#event_start_date_time").timepicker({ 'timeFormat': 'H:i:s' });
    $("#event_end_date_time").timepicker({ 'timeFormat': 'H:i:s' });
    
  });

</script>

app/views/events/get_events_by_format.json.erb.erb
<%= @events %>

app/views/events/get_events_by_format.xml.erb.erb
<%= @events %>

app/views/events/new.html.erb
<p><%= link_to 'Home', root_path %></p>
<h2>Neue Veranstaltung anlegen</h2>
<%= render 'event_form' %>

app/views/events/show.html.erb
<style type="text/css">

table {
  border-width: 0;
  border-style: none;
  border-color: #0000ff;
  border-collapse: collapse;
  height:120px;
  width:120px;
 }
td {
  border-width: 0;
  border-style: none;
  border-color: #0000ff;
  border-collapse: collapse;
  padding: 0;
  margin: 0;
  width: 1px;
  //height: 10px;
}

td.black { background-color: #000; }
td.white { background-color: #fff; }

</style>

<p><%= link_to 'Home', root_path %></p>
<h4 id="map_notifier" style="display:none"></h4>


<div style="margin-top:70px; width:800px; float:left">
  <%= render 'layouts/navibar', :all_venues => @all_venues, :all_cats => @all_event_cats, :federal_clicked => @federal_state_clicked, :regional_clicked => @region_clicked, :main_cat_clicked => @main_cat_clicked, :sub_cat_clicked => @sub_cat_clicked %>

  <%= render 'layouts/user_panel' %>

</div>


<div style="float:right; margin-top:-3.5%; width:300px; text-align:center">
  <div id="event_map" style="width:400px; height:300px"></div>
  
  <h3>Veranstaltungsort</h3>
  <p><%= @event.venue %></p>
  
  <h3>Adresse</h3>
  <p><%= @event.address %></p>
  <p id="address" style="display:none"><%= raw @event.latitude.to_s << " "<< @event.longitude.to_s %></p>
  
  <h3>Kosten</h3>
  <% if @event.venue_url.length > 0 %>
    <p><%= @event.costs %></p>
  <% else %>
    <p>Keine Kosten angegeben</p>
  <% end %>

  <h3>Website</h3>
  <% if @event.venue_url.length > 0 %>
    <p><%= link_to 'Zur Webseite', (if @event.venue_url.index('http://') == 0 then @event.venue_url else ('http://' << @event.venue_url) end) %></p>
  <% else %>
    <p>Keine Webseite angegeben</p>
  <% end %>

  <h3>E-Mail</h3>
  <% if @event.email.length > 0 %>
    <p><%= @event.email %></p>
  <% else %>
    <p>Keine E-Mail Adresse angegeben</p>
  <% end %>

  <h3>Tel. Nr.</h3>
  <% if @event.tel_nr.length > 0 %>
    <p><%= @event.tel_nr.sub(/^00/, '') %></p>
  <% else %>
    <p>Keine Tel. Nr. angegeben</p>
  <% end %>

</div>


<div style="margin-top:70px; width:650px; float:left">
  <h2><%= @event.title %></h2>
  
  <!-- paperclip image, deactivated because of heroku 
    <%# image_tag @event.image.url(:medium), :style => 'width:250px; height:190px; float:left' %>-->
  <% if @event.image_url && @event.image_url.length > 0 %>
    <img src="<%= @event.image_url %>" width="250px" height="190px" style="float:left" />
  <% end %>
  
  <div style="width:170px; margin-left:8px; float:left">
  
    <h3><%= @event.main_category %>/<%= @event.sub_category %></h3>
    
    <p>
      <% if @event.start_date >= Date.today %>
        <p><b>Start-Datum: <%= @event.start_date.strftime('%d.%b %Y') %> um <%= @event.start_date_time.strftime('%H:%M:%S') %></b></p>
        <p><b>Ende-Datum: <%= @event.end_date.strftime('%d.%b %Y') %> um <%= @event.end_date_time.strftime('%H:%M:%S') %></b></p>
      <% else %>
        
        <% if @event.repeat_dates.length > 0 %>
          <b>Das Start-Datum ist bereits abgelaufen, nächste Daten sind:</b>
          <%= render 'layouts/formatted_dates', :event => @event, :max_num => 5 %>
        <% else %>
          <b>Veranstaltung ist bereits abgelaufen.</b>
        <% end %>
      <% end %>
    </p>
    
    <%= render 'layouts/qr_coder', :string_to_encode => pdf_event_url(@event) %>
  
    <% url = "window.open('https://www.google.com/calendar/render?action=TEMPLATE&dates=" + @event.start_date.strftime('%Y%m%d') + @event.start_date_time.strftime('T%H%M%SZ') + "/" + @event.end_date.strftime('%Y%m%d') + @event.end_date_time.strftime('T%H%M%SZ') + "&details=" + @event.description.split(/\r\n|\"/).join + "&sprop=website:" + @event.venue_url.html_safe + "&text=" + @event.title.html_safe + "&pli=1&sf=true&output=xml', '_blank'); return false" %>
    <b><%= link_to 'Google Cal', '#', :onclick => url.html_safe %></b>
    <b><%= link_to 'ICal & Outlook', ics_event_path(@event.id) %></b>
    <p><b><%= link_to 'Als PDF anzeigen', pdf_event_path(@event.id) %></b></p>
    
    <% if (current_user && @event.user && current_user.id == @event.user.id) || (current_user && current_user.federal_user && @event.user && @event.user.regional_user) || current_admin %>
      <p><b><%= link_to 'Bearbeiten', edit_event_path(@event.id) %></b></p>
      <p><b><%= link_to 'Löschen', event_path(@event.id), :method => :delete %></b></p>
    <% end %>
  </div>
  
  <h4 style="margin-top:35%"><%= @event.description.html_safe %></h4>
  
  <br />
  <div id="fb-root"></div>
  <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script>
  <fb:comments href="http://event-corp.herokuapp.com/events/<%= @event.id %>"></fb:comments>
  
</div>