config/routes.rb
EventApp::Application.routes.draw do
  
  mount Ckeditor::Engine => "/ckeditor"
  
  get "admin/new"

  get "admin/create"

  devise_for :admins, :controllers => { :sessions => "admin" }

  get "registration/new"

  devise_for :users, :controllers => { :sessions => "users", :registrations => "registration" }

  resources :events
    match 'eventFeedRss/:ids' => 'Events#get_rss_feed', :as => 'event_feed'
    match 'allEventFeedRss' => 'Events#get_all_rss_feed', :as => 'all_event_feed'
    match 'getEventsByFormat/:attr/:value' => 'Events#get_events_by_format'
    match 'pdfEvent/:id' => 'Events#pdf_event', :as => 'pdf_event'
    match 'pdfEvents/:ids' => 'Events#pdf_events', :as => 'pdf_events'
    match 'icsEvent/:id' => 'Events#ics_event', :as => 'ics_event'
    
  get "venue/index"
  
  controller :Venue do
    match 'eventHighlights/:cat/:highlight' => :index, :as => 'event_highlight'
    match 'federalCountry/:country' => :get_federal_country, :as => 'get_federal_country'
    match 'venue/:city' => :get_venue, :as => 'get_venue'
    match 'catMainEvents/:cat' => :get_main_cat_events, :as => 'get_main_cat_events'
    match 'catSubEvents/:cat' => :get_sub_cat_events, :as => 'get_sub_cat_events'
    match 'date/:start_date' => :get_events_by_date
    match 'contact' => :contact, :as => 'contact'
    match 'sendContactMail' => :send_contact_mail, :as => 'send_contact_mail'
    match 'searchSurroundingEvents' => :search_surrounding_events, :as => 'search_surrounding_events'
    match 'locationSearch' => :get_events_by_geocoding, :as => 'get_events_by_geocoding'
    match 'userlist' => :get_user_list, :as => 'get_user_list'
    match 'sitemap.xml' => :sitemap
  end
  
  controller :Ajax do
    match 'searchForEvents/:search' => :search_events
  end
  
  root :to => 'Venue#index'
  # See how all your routes lay out with "rake routes"

end

app/controllers/venue_controller.rb
class VenueController < ApplicationController
  
  before_filter :get_navi_vars, :only => [:index, :get_main_cat_events, :get_sub_cat_events, :get_federal_country, :get_venue, :get_events_by_date, :get_events_by_geocoding, :get_user_list]
  before_filter :get_sponsored_events
  
  def index
    if (params[:cat] == 'federal' || params[:cat] == 'regional') && params[:highlight] == 'true'
      if params[:cat] == 'federal'
        @events = Event.where( :federal_highlight => true ).order('start_date asc')
      elsif params[:cat] == 'regional'
        @events = Event.where( :regional_highlight => true ).order('start_date asc')
      end
    else
      @events = Event.search(params[:search])
    end
  end
  
  def get_main_cat_events
    @events = Event.find(:all, :conditions => ['main_category = ?',params[:cat]], :order => "start_date asc")
    @main_cat_clicked = params[:cat]
    render 'index'
  end
  
  def get_sub_cat_events
    @events = Event.find(:all, :conditions => ['sub_category = ?',params[:cat]], :order => "start_date asc")
    @main_cat_clicked = Categories.get_main_cat_by_sub_cat params[:cat]
    @sub_cat_clicked = params[:cat]
    render 'index'
  end
  
  def get_federal_country
    @events = Event.find(:all, :conditions => ['province = ?',params[:country]], :order => "start_date asc")
    @federal_state_clicked = params[:country]
    render 'index'
  end
  
  def get_venue
    @events = Event.find(:all, :conditions => ['city = ?',params[:city]], :order => "start_date asc")
    @federal_state_clicked = Venues.get_federal_countries_by_vene params[:city]
    @region_clicked = params[:city]
    render 'index'
  end
  
  def get_events_by_date
    search_date = Date.parse(URI.unescape(params[:start_date]))
    
    @events = []
    Event.all.each do |event|
      
      if event.start_date == search_date
        @events << event
      else
        if event.repeat_dates != 'never'
          dates = event.repeat_dates.split(' ')
          dates.each do |date|
            if search_date.strftime('%Y-%m-%d') == date
              @events << event
            end
          end
        end
      end
    end
    
    render 'index'
  end
  
  def get_events_by_geocoding
    marker_place = Geocoder.search(params[:latlng])
    if marker_place.nil?
      redirect_to :root, :notice => 'Die Google-API kann momentan nicht benutzt werden.'
      return
    end
    
    @events = []
    
    Event.all.each do |event|
      distance_diff = event.distance_to(marker_place[0].address)
      if distance_diff && (distance_diff *1.6) <= 20 # radius 20 km
        @events << event
      end
    end
    render 'index'
  end
  
  def get_user_list
    if !current_admin
      redirect_to :root, :notice => 'Keine Berechtigung!'
      return 
    end
    
    @users = User.find(:all, :order => "email asc")
  end
  
  def contact
  end
  
  def send_contact_mail
    user = '(Nicht registriert!)'
    if current_user
      user = current_user
    elsif current_admin
      user = current_admin
    end
    UserMailer.send_contact_mail(user, params[:subject],params[:body]).deliver
    redirect_to :root, :notice => 'Wir werden ihre Nachricht in kürze beantworten.'
  end
  
  def search_surrounding_events
    if request.location && request.location.city.length > 0
      @location = request.location.city + ', ' + request.location.country
    else
      @location = ''
    end
  end
  
  def sitemap
    render :text => File.read(Dir.pwd << 'public/sitemap.xml')
  end
  
  private
  
  def get_sponsored_events
    @sponsored_events = Event.where( :sponsored => true ).order('start_date asc')
  end
  
end

app/helpers/venue_helper.rb
module VenueHelper
end

app/views/venue/contact.html.erb
<%= link_to 'Home', root_path %>

<h3>Sende uns eine Mail</h3>
<%= form_tag send_contact_mail_path, :method => :get do %>

  <p><p><%= label_tag 'Betreff' %></p>
  <p><%= text_field_tag :subject, '', { :size => '130' } %></p></p>
  
  <p><p><%= label_tag 'Nachricht' %></p>
  <p><%= cktext_area_tag :body, '', :toolbar => 'Easy', :width => 888, :height => 270 %></p></p>
  
  <p><%= submit_tag 'abschicken', { :name => nil, :onclick => 'if(document.forms[0].subject.value.length > 0 && CKEDITOR.instances[\'body\'].getData().length > 0){document.forms[0].submit(); }else{ alert(\'Bitte Betreff und Nachricht-Textfelder ausfüllen!\');return false;}'.html_safe } %>
  <%= button_tag 'Zurück', :type => 'button', :name => nil, :onclick => 'window.location = \'http://event-corp.herokuapp.com/\''.html_safe %></p>
  
<% end %>

app/views/venue/get_user_list.html.erb
<%= link_to 'Home', root_path %>

<h3>Userliste</h3>

<%= render 'layouts/navibar', :all_venues => @all_venues, :all_cats => @all_event_cats, :federal_clicked => @federal_state_clicked, :regional_clicked => @region_clicked, :main_cat_clicked => @main_cat_clicked, :sub_cat_clicked => @sub_cat_clicked %>
<%= render 'layouts/user_panel' %>

<ul style="margin-top:100px">
<% for user in @users %>
  <li>
    <h3><%= 'Username:' << user.email %></h3>
    <%= button_to "User bearbeiten", edit_user_registration_path(user.id), :method => :get %>
    <%= button_to "User löschen (Veranstaltungen werden mitgelöscht)", { :controller => 'registration', :action => 'destroy', :id => user.id }, :confirm => "Wirklich löschen?", :method => :delete %>
  </li>
  <% if !user.events.empty? %>
    <li>
      <ul>
        <li>Veranstaltungen:</li>
        <% for event in user.events %>
          <li><%= link_to event.title << ' Kat. ' << event.main_category << '/' << event.sub_category, event_path(event.id) %></li>
        <% end %>
      </ul>
    </li>
  <% else %>
    <li>Keine Veranstaltungen</li>
  <% end %>
<% end %>
</ul>

app/views/venue/index.html.erb
 
<p><%= link_to 'Home', root_path %></p>

<h1>Veranstaltungen</h1>

<div id="leftcol">

<%= render 'layouts/navibar', :all_venues => @all_venues, :all_cats => @all_event_cats, :federal_clicked => @federal_state_clicked, :regional_clicked => @region_clicked, :main_cat_clicked => @main_cat_clicked, :sub_cat_clicked => @sub_cat_clicked %>

<% if current_user || current_admin %>
  <%= render 'layouts/user_panel' %>
<% end %>

<%= render 'layouts/event_list', :events => @events, :federal_state_clicked => @federal_state_clicked, :region_clicked => @region_clicked %>

</div>

<div id="rightcol">

  <%= render 'layouts/calender', :entries => @events %>
  
  <div id="additional">
  
    <table>
      <tr><td><%= link_to 'Alle Veranstaltungen', root_path %></td></tr>
      <tr><td><%= link_to 'Alle Bundes-Highlights', event_highlight_path('federal', 'true') %></td></tr>
      <tr><td><%= link_to 'Alle Regional-Highlights', event_highlight_path('regional', 'true') %></td></tr>
      <tr><td><%= link_to 'Umfeldsuche', search_surrounding_events_path %></td></tr>
      
      <% if current_user || current_admin %>
        <tr><td><%= link_to_if current_user || current_admin, 'Verstanstaltung hinzufügen', new_event_path %></td></tr>
        <tr><td><%= link_to_if current_admin, 'User hinzufügen', new_user_registration_path %></td></tr>
        <tr><td><%= link_to_if current_admin, 'Userliste', get_user_list_path %></td></tr>
      <% else %>
        <tr><td><%= link_to_if !current_admin, 'Admin Login', new_admin_session_path %></tr>
        <tr><td><%= link_to_if !current_user && !current_admin, 'Login', new_user_session_path %></tr>
      <% end %>
      
      <tr><td><%= link_to 'RSS Feed', event_feed_path( get_event_ids(@events) ) << '.rss' %></td></tr>
      <tr><td><%= link_to 'Kontakt', contact_path %></td></tr>
      
    </table>
  
  </div>
  <p><%= link_to 'Alle als PDF ansehen', pdf_events_path( get_event_ids(@events) ) %></p>
  
</div>

app/views/venue/search_surrounding_events.html.erb
<%= link_to 'Home', root_path %>
<h3>Suche Veranstaltungen mit Hilfe der Texteingabe oder der Map</h3>

<%= form_tag get_events_by_geocoding_path, :method => 'get' do %>
  <%= hidden_field_tag 'latlng', '', :id => 'latlng' %>
  <%= hidden_field_tag 'currentLocation', @location, :id => 'currentLocation' %>
  <%= text_field_tag 'adresse', '', :placeholder => 'Suche Veranstaltungen nach Adresse', :onkeyup => 'document.getElementById("latlng").value = this.value', :size => '130' %>
  <%= submit_tag 'Suchen', :name => nil %>
<% end %>

<% if @location.length > 0 %>
  <b>Sie sind in der Region <%= @location %> lokalisiert.</b>
<% end %>

<h3>Ziehe den Marker auf die gewünschte Stelle, wo nach Veranstaltungen gesucht werden soll</h3>
<div id="search_map" style="height:800px; width:888px"></div>


<% if !@sponsored_events.empty? %>
  <!-- sponsored events -->

  <table style="display:none" id="sponsoredEvents">
    <% @sponsored_events.each do |e| %>
      <tr>
        <td><%= e.title %></td>
        <td><%= e.latitude %></td>
        <td><%= e.longitude %></td>
        <td><%= e.address %></td>
        <td><%= e.image_url %></td>
        <td><%= e.id %></td>
      </tr>
    <% end %>
  </table>

<% end %>