config/routes.rb
EventApp::Application.routes.draw do
  
  mount Ckeditor::Engine => "/ckeditor"
  
  get "admin/new"

  get "admin/create"

  devise_for :admins, :controllers => { :sessions => "admin" }

  get "registration/new"

  devise_for :users, :controllers => { :sessions => "users", :registrations => "registration" }

  resources :events
    match 'eventFeedRss/:ids' => 'Events#get_rss_feed', :as => 'event_feed'
    match 'allEventFeedRss' => 'Events#get_all_rss_feed', :as => 'all_event_feed'
    match 'getEventsByFormat/:attr/:value' => 'Events#get_events_by_format'
    match 'pdfEvent/:id' => 'Events#pdf_event', :as => 'pdf_event'
    match 'pdfEvents/:ids' => 'Events#pdf_events', :as => 'pdf_events'
    match 'icsEvent/:id' => 'Events#ics_event', :as => 'ics_event'
    
  get "venue/index"
  
  controller :Venue do
    match 'eventHighlights/:cat/:highlight' => :index, :as => 'event_highlight'
    match 'federalCountry/:country' => :get_federal_country, :as => 'get_federal_country'
    match 'venue/:city' => :get_venue, :as => 'get_venue'
    match 'catMainEvents/:cat' => :get_main_cat_events, :as => 'get_main_cat_events'
    match 'catSubEvents/:cat' => :get_sub_cat_events, :as => 'get_sub_cat_events'
    match 'date/:start_date' => :get_events_by_date
    match 'contact' => :contact, :as => 'contact'
    match 'sendContactMail' => :send_contact_mail, :as => 'send_contact_mail'
    match 'searchSurroundingEvents' => :search_surrounding_events, :as => 'search_surrounding_events'
    match 'locationSearch' => :get_events_by_geocoding, :as => 'get_events_by_geocoding'
    match 'userlist' => :get_user_list, :as => 'get_user_list'
    match 'sitemap.xml' => :sitemap
  end
  
  controller :Ajax do
    match 'searchForEvents/:search' => :search_events
  end
  
  root :to => 'Venue#index'
  # See how all your routes lay out with "rake routes"

end

app/views/layouts/_all_events_list.html.erb
<!-- js-plugin taken out -->

<div id="section-divider">
    <ol>
      <% num = 0 %>
      <% for event in events %>
        
        <% if (num % 10) == 0 %>
          <li>
          <h2><%= ('ab ' << num.to_s << ' bis ' << (num+9).to_s) %></h2>
          <div style="overflow-y:auto">
        <% end %>
        
        <% num += 1 %>
            <p>
              <h2><%= event.title %></h2>
              <div>
                <p>
                  <%= render 'layouts/formatted_dates', :event => event, :max_num => 3 %>
                </p>
                <% if carousel_activated %>
                  <p><%= event.main_category %></p>
                <% else %>
                  <p><%= event.main_category << '/' << event.sub_category %></p>
                <% end %>
                <!--<p><%# image_tag event.image.url(:thumb) %></p>-->
                <% if event.image_url && event.image_url.length %>
                  <p><img src="<%= event.image_url %>" width="300" height="300" /></p>
                <% end %>
                <p><%= raw truncate(event.description, :length => 300) %></p>
                <p><%= link_to 'Zeigen', event_path(event.id) %></td>
                <%= link_to 'Als PDF anzeigen', pdf_event_path(event.id) %>
                <%= link_to_if (current_user && event.user && current_user.id == event.user.id) || (current_user && current_user.federal_user && event.user && event.user.regional_user) || current_admin, 'Bearbeiten', edit_event_path(event.id) %>
                <%= link_to_if (current_user && event.user && current_user.id == event.user.id) || (current_user && current_user.federal_user && event.user && event.user.regional_user) || current_admin, 'Löschen', event_path(event.id), :method => :delete %></p>
              </div>
            </p>
        
        <% if (num % 10) == 0 %>
          </div>
          </li>
        <% end %>
        
      <% end %>
      
      <% if (num % 10) != 0 %>
        </div>
        </li>
      <% end %>
      
    </ol>
</div>

app/views/layouts/_calender.html.erb
<div id="main_notifier" style="display: none; font-size: 20px; font-weight:bold; position:absolute; top:140px; z-index:100;">
  <%= notice %>
  <%= alert %>
</div>
  
<div id="jcal"></div>

<script type='text/javascript'>

$(document).ready(function() {
  
  $.calendars.picker.regional['de'] = {
		renderer: $.calendars.picker.defaultRenderer,
		prevText: '&#x3c;zurück', prevStatus: 'letzten Monat zeigen',
		prevJumpText: '&#x3c;&#x3c;', prevJumpStatus: '',
		nextText: 'Vor&#x3e;', nextStatus: 'nächsten Monat zeigen',
		nextJumpText: '&#x3e;&#x3e;', nextJumpStatus: '',
		currentText: 'heute', currentStatus: '',
		todayText: 'heute', todayStatus: '',
		clearText: 'löschen', clearStatus: 'aktuelles Datum löschen',
		closeText: 'schließen', closeStatus: 'ohne Änderungen schließen',
		yearStatus: 'anderes Jahr anzeigen', monthStatus: 'anderen Monat anzeigen',
		weekText: 'Wo', weekStatus: 'Woche des Monats',
		dayStatus: 'Wähle D, M d', defaultStatus: 'Wähle ein Datum',
		isRTL: false
	};
	$.calendars.picker.setDefaults($.calendars.picker.regional['de']);
  
  $('#jcal').calendarsPicker({ 
    calendar: $.calendars.instance('gregorian', 'de'),
    onSelect: function(dates) {
      window.location = "http://" + window.location.host + "/date/" + dates;
    }
  });

});

</script>

app/views/layouts/_carousel.html.erb
<div id="<%= classname %>">
  <h2><%= title %></h2>
  
  <ul class="<%= classname_carousel %>">				
    <% events.each do |event| %>
      <li>
        <% if event.image_url && event.image_url.length > 0 %>
          <img src="<%= event.image_url %>" width="270px" height="180px" />
        <% end %>
        
        <span class="feat_date"><%= event.start_date.strftime('%d.%b %Y') %></span>
        <span class="ch_h"><%= event.title %></span>
        <h6><%= event.main_category %> - <%= event.sub_category %></h6>
   			<p><%= raw truncate(event.description, :length => 230) %></p>
        <p><%= link_to 'Weiterlesen', event_path(event.id) %></p>
        <div class="ch_act"><p><%= link_to 'Als PDF anzeigen', pdf_event_path(event.id) %>
        
          <% if (current_user && event.user && current_user.id == event.user.id) || (current_user && current_user.federal_user && event.user && event.user.regional_user) || current_admin %>
            <%= link_to 'Bearbeiten', edit_event_path(event.id) %>
            <%= link_to 'Löschen', event_path(event.id), :method => :delete %></p>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>

  <span class="<%= classname_prev_button %>">prev</span>
  <span class="<%= classname_next_button %>">next</span>
</div>

app/views/layouts/_event_list.html.erb
<div>
  <% highlight_events = [] %>
  <% all_events = [] %>
  
  <% for event in events %>
    
    <% if federal_state_clicked && !region_clicked && event.federal_highlight %>
      <% highlight_events << event %>
    
    <% elsif region_clicked && !federal_state_clicked && event.regional_highlight %>
      <% highlight_events << event %>
    
    <% elsif !federal_state_clicked && !region_clicked %>
      <% if event.federal_highlight || event.regional_highlight %>
        <% highlight_events << event %>
      <% end %>
      
    <% end %>
    
    <% all_events << event %>
    
  <% end %>
  
  <% if !highlight_events.empty? %>
    <%= render 'layouts/carousel', :events => highlight_events, :title => 'Top Veranstaltungen', :classname => 'car_high', :classname_carousel => 'carousel', :classname_next_button => 'carousel_next', :classname_prev_button => 'carousel_prev' %>
  <% end %>
  
  <% if !@sponsored_events.empty? %>
    <%= render 'layouts/carousel', :events => @sponsored_events, :title => 'Empfohlene Veranstaltungen', :classname => 'car_sponsor', :classname_carousel => 'carousel2', :classname_next_button => 'carousel2_next', :classname_prev_button => 'carousel2_prev' %>
  <% end %>
 
</div>

<% if !all_events.empty? %>

    <div id="section-divider">
      
      <ul class="eventlistener">
        <% all_events.each do |event| %>
        
          <li class="event">
            <div class="event_h"><%= event.title %><span class="feat_date"><%= event.start_date.strftime('%d.%b %Y') %></span></div>
                                
            <% if event.image_url && event.image_url.length > 0 %>
              <img src="<%= event.image_url %>" width="180px" height="120px" />
            <% end %>
            <h6><%= event.main_category %> - <%= event.sub_category %></h6>
            <p><%= raw truncate(event.description, :length => 230) %></p>
            <p><%= link_to 'Weiterlesen', event_path(event.id) %></p>
            <div class="ch_act"><p><%= link_to 'Als PDF anzeigen', pdf_event_path(event.id) %></p>
            
            <% if (current_user && event.user && current_user.id == event.user.id) || (current_user && current_user.federal_user && event.user && event.user.regional_user) || current_admin %>
              <%= link_to 'Bearbeiten', edit_event_path(event.id) %>
              <%= link_to 'Löschen', event_path(event.id), :method => :delete %></p>
            <% end %>
          </li>
          
        <% end %>
      </ul>
    </div>

  <%# render 'layouts/all_events_list', :events => all_events, :carousel_activated => if !highlight_events.empty? || !sponsored_events.empty? then true else false end %>
<% end %>


<script type="text/javascript">

  $(document).ready(function() {
    
    $("ul.carousel").simplecarousel({
        slidespeed: 700,
        auto: 5000,
        width: 680,
        height: 240,
        //fade: 400,
        pagination: true,
        next: $('.carousel_next'),
        prev: $('.carousel_prev')
    });
    
    $("ul.carousel2").simplecarousel({
        //slidespeed: 700,
        auto: 5000,
        width: 680,
        height: 240,
        fade: 400,
        pagination: true,
        next: $('.carousel2_next'),
        prev: $('.carousel2_prev')
    });
    
    //$("#section-divider").liteAccordion();
    
    // show hits altogether
    var originalDomain = "http://" + window.location.host + '/';
    if( window.location.href.length > originalDomain.length )
      $('#main_notifier').html("<%= @events.count.to_s + ' Treffer'%>");
    
  });
  
</script>

app/views/layouts/_formatted_dates.html.erb
<% if event.repeat_dates && event.repeat_dates.length != 0 %>
    
  <% num = 0 %>
  <p><b>
    <% event.repeat_dates.split(' ').each do |date| %>
      
        <% if date >= Date.today.to_s %>
        
          <% num += 1 %>
          
          <% if (num+1) < max_num && event.repeat_dates.split(' ').last != date %>
            <%= DateTime.parse(date).strftime('%d.%b %Y') + '|' %>
          <% else %>
            <%= DateTime.parse(date).strftime('%d.%b %Y') %>
          <% end %>
          
          <% if num == max_num %>
            <% break %>
          <% end %>
          
        <% end %>
    <% end %>
  </b></p>
  
<% end %>

app/views/layouts/_navibar.html.erb
<div id="nav_search">

    <ul class="menu" id="menu">
      
      <!-- federal and regional categories -->
      
          <% if federal_clicked || regional_clicked %>
            
            <% if regional_clicked %>
              <li><a href="#" class="menulink"><%= regional_clicked %></a>
                <ul>
                
            <% else %>
              
              <li><a href="#" class="menulink"><%= federal_clicked %></a>
                <ul>
                
                  <% all_venues[federal_clicked].each do |venues| %>
                    <li><%= link_to (venues[:name].to_s + '(' + venues[:number].to_s + ')'), get_venue_path(venues[:name]) %></li>
                  <% end %>
                  
            <% end %>
          <% else %>
          
            <li><a href="#" class="menulink">Bundesland/Ort</a>
                <ul>
                
                  <% all_venues.each do |fed_name,venues| %>
                    
                    <% num = 0 %>
                    <% for number_alt in venues %>
                      <% num += number_alt[:number].to_i %>
                    <% end %>
                    
                    <li><%= link_to (fed_name + '(' + num.to_s + ')'), get_federal_country_path(fed_name), :class  => 'sub' %>
                    
                      <ul>
                        <% for venue in venues %>
                        
                          <% if venues.first == venue %>
                            <li class="topline"><%= link_to (venue[:name] + '(' + venue[:number].to_s + ')'), get_venue_path(venue[:name]) %></li>
                          <% else %>
                            <li><%= link_to (venue[:name] + '(' + venue[:number].to_s + ')'), get_venue_path(venue[:name]) %></li>
                          <% end %>
                            
                        <% end %>
                      </ul>
                      
                    </li>
                  <% end %>
            
          <% end %>
      
        </ul>
      </li>
      
      
      <!-- main and sub categories -->
      
          <% if main_cat_clicked || sub_cat_clicked %>
            
            <% if sub_cat_clicked %>
              <li><a href="#" class="menulink"><%= sub_cat_clicked %></a>
                <ul>
                
            <% else %>
              
              <li><a href="#" class="menulink"><%= main_cat_clicked %></a>
                <ul>
                
                  <% all_cats[main_cat_clicked].each do |sub| %>
                    <li><%= link_to (sub[:name].to_s + '(' + sub[:number].to_s + ')'), get_sub_cat_events_path(sub[:name]) %></li>
                  <% end %>
                  
            <% end %>
          <% else %>
          
            <li><a href="#" class="menulink">Kategorie</a>
            <ul>
              <% all_cats.each do |cat_name,sub_cats| %>
                
                <% num = Event.find(:all, :conditions => ['main_category = ?',cat_name]).count %>
                
                <li><%= link_to (cat_name + '(' + num.to_s + ')'), get_main_cat_events_path(cat_name), :class  => 'sub' %>
                
                  <ul>
                    <% for sub_cat in sub_cats %>
                    
                      <% if sub_cats.first == sub_cat %>
                        <li class="topline"><%= link_to (sub_cat[:name] + '(' + sub_cat[:number].to_s + ')'), get_sub_cat_events_path(sub_cat[:name]) %></li>
                      <% else %>
                        <li><%= link_to (sub_cat[:name] + '(' + sub_cat[:number].to_s + ')'), get_sub_cat_events_path(sub_cat[:name]) %></li>
                      <% end %>
                        
                    <% end %>
                  </ul>
                  
                </li>
              <% end %>
            
          <% end %>
      
        </ul>
      </li>
      
      
      <li>
        <%= form_tag root_path, :method => 'get', :onsubmit => '//return false' do %>
     
          <p><%= text_field_tag :search, params[:search], :placeholder => 'Suche', :id => 'searchField', :style => "width:250px; height:28px" %>
          <p><div id ='searchResults' style="position: absolute; display:none;"></div></p>
        <% end %>
        
      </li>
      
    </ul>

</div>

<script type="text/javascript">
	
  // dropdown
  var menu=new menu.dd("menu");
  menu.init("menu","menuhover");
  
  $(document).ready(function(){
     
    
    // navi:auto-selection field
    var arrowLoc = 0;
    var arrowMoved = false;
    var currentChildren = null;
    
    $('#searchField').keyup(function(event) {
      
      // arrow-buttons feature deactivated
      
      arrowMoved = false;
      
      if($('#searchField').val().length == 0){
        $('#searchResults').html('');
        $('#searchResults').css('display', 'none');
      }
      else{
        $('#searchResults').css('display', 'inline');
        $('#searchResults').css('width', $('#searchField').css('width'));
        
        /*
        var results = (document.getElementById('searchResults').children && document.getElementById('searchResults').children[0] && document.getElementById('searchResults').children[0].children) ? document.getElementById('searchResults').children[0].children : false;
          console.log(event.keyCode);
        if(event.keyCode == 40){ // arrow down
          
          arrowMoved = true;
          
          if(results){
   
            if(arrowLoc != results.length-1){
              arrowLoc++;
              results[arrowLoc - 1].style.backgroundColor = '#c3c3c3';
            }
            else{
              arrowLoc = 0;
              results[results.length - 1].style.backgroundColor = '#c3c3c3';
            }
            
            results[arrowLoc].style.backgroundColor = 'red';
            currentChildren = results[arrowLoc];
          }
        }
        else if(event.keyCode == 38){ // arrow up
          
          arrowMoved = true;
          
          if(results){
          
            if(arrowLoc != 0){
              arrowLoc--;
              results[arrowLoc + 1].style.backgroundColor = '#c3c3c3';
            }
            else{
              arrowLoc = results.length-1;
              results[0].style.backgroundColor = '#c3c3c3';
            }
              
            results[arrowLoc].style.backgroundColor = 'red';  
            currentChildren = results[arrowLoc];
          }
        }
        else if(event.keyCode == 13 && currentChildren){ // enter
          window.location = "http://" + window.location.host + "/events/" + currentChildren.id;
          currentChildren = null;
        }
        */
      }
      
      
      if(!arrowMoved && $('#searchField').val().length){
        arrowLoc = 0;
        currentChildren = null;
        $('#searchResults').load("http://" + window.location.host + "/searchForEvents/" + $('#searchField').val() + " #eventResults", function(data) {
          $(this).html(data);
        });
      }
      
    });
    
    // fade out search result-div
    var resultDivEntered = false;
    $(document).mouseover(function(event){
      
      if(event.target.nodeName == 'A')
        resultDivEntered = true;
        
      if(event.target && event.target.nodeName != 'A' && resultDivEntered){
        $('#searchResults').fadeOut(100);
        resultDivEntered = false;
      }
      
    });
    
  });
  
</script>

app/views/layouts/_qr_coder.html.erb
<table style="margin-left:205px; margin-top:-142px">
<% qr = RQRCode::QRCode.new(string_to_encode, :size => 6, :level => :h ) %>
<% qr.modules.each_index do |x| %>
  <tr>  
  <% qr.modules.each_index do |y| %>
   <% if qr.dark?(x,y) %>
    <td class="black"/>
   <% else %>
    <td class="white"/>
   <% end %>
  <% end %>
  </tr>
<% end %>
</table>

app/views/layouts/_user_panel.html.erb
<div style="width:100%">

  <div style="width:150px; float:left">
    <% if current_user %>
      <h3>User</h3>
      <%= current_user.email %>
      <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
    <% elsif current_admin %>
      <h3>Als Admin eingeloggt</h3>
      <%= link_to 'Logout', destroy_admin_session_path, :method => :delete %>
    <% end %>
  </div>

  <div id="main_notifier" style="width: 250px; float: right; display: none; font-size: 20px; font-weight: bold;">
    <%= notice %>
    <%= alert %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="google-site-verification" content="netBakOUgTB8G2u7LF5N7WMhWDKS6wHrXfsVl2abZsA" />
  <meta property="fb:admins" content="100002171584974"/>
  <meta property="fb:app_id" content="320227761392901"/>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
  <%= auto_discovery_link_tag(:rss, {:controller => "Events", :action => "get_all_rss_feed"}) %>
  
  <title>EventApp</title>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <!--[if lt IE 9]>
  <link  type="text/css"  href="http://chriscoyier.github.com/MovingBoxes/css/movingboxes-ie.css"  rel="stylesheet" media="screen" />
  <![endif]-->

  <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
  <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDq8dsh-CgT1r0D4o96H9tEYbIakrGMcnI&sensor=true"></script>
  <script src="http://google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.5/src/infobox_packed.js" type="text/javascript"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.0/jquery.js"></script>
  
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
  
</head>
<body>

<div id="main">
  
  <%= yield %>

</div>
</body>
<script type="text/javascript">

  $(document).ready(function() {
    
    if( document.getElementById('main_notifier') && $('#main_notifier').html().length ){
      $('#main_notifier').css('display','inline');
      $('#main_notifier').fadeOut(8000);
    }
    
  });
  
</script>
</html>